# Database credentials
database:
  # antingen denna
  file: "" 
  # eller alla dessa (om file Ã¤r blankt)
  sql-user: "root"            #
  sql-pass: "Hejsan123"
  sql-server: "mysql"
  sql-database: "salary"
  sql-port: 3306

redis:
  server: "localhost:6379"

sso:
  clientId:  "StudentPortal"
  clientSecret:  "EM4WKTSRUXVWG5RBTXC3VPOBTMF5Y3SL"
  baseAddress:  "https://localhost:44375/"
  backBaseAddress: "https://localhost:8080/"

